//Перевод

document.addEventListener("DOMContentLoaded", () => {
    const languageSelect = document.getElementById("language");
    const translateElements = document.querySelectorAll("[data-translate]");

    // Объект с переводами
    const translations = {
        ru: {
            labelLanguage: "Язык:",
            loadingTitle: "Загружаем Ecrous Engine...",
            loadingMessage: "Не переживайте, все готово будет через пару секунд!",
            myProjects: "Мои Проекты",
            xStore: "XStore",
            blackStore: "BlackStoreRu",
            profile: "Профиль",
            thanks: "Благодарности",
            centerText: "Похоже, у вас еще нет проектов.<br>Создайте новый или импортируйте!",
            ThanksCommunity: "Спасибо от сообщества Ecrous Engine!",
            Autors: "Авторы",
            Donors: "Доноры",
            License: "Лицензия",
            HappyBirsday: "ДР!",
            HappyBirsdayEnd: "Прошедшие ДР",
            DaniilDomashnev: "Даниил Домашнев",
            ThemEditor: "Тема Редактора:",
            ThemBlack: "Темная",
            ThemWhite: "Светлая",
            russian: "Русский",
            english: "Английский",
            ukraine: "Украинский",
            espano: "Испанский",
            deutsch: "Немецский",
            FilePath: "Путь к файлу:",
            Gravity: "Гравитация",
            Review: "Обзор",
            Settings: "Настройки",
            Community: "Сообщество",
            Profile: "Профиль",
            OpenProfile: "Сменить имя",
            Promocodes: "Промокоды",
            InputPromocode: "Введите промокод",
            ApplyPromocode: "Применить промокод",

            labelfonts: "Шрифт:",
            SelectCustom: "Выберите шрифт",
        },
        en: {
            labelLanguage: "Language:",
            loadingTitle: "Loading Ecrous Engine...",
            loadingMessage: "Don't worry, everything will be ready in a few seconds!",
            myProjects: "My Projects",
            xStore: "XStore",
            blackStore: "BlackStoreRu",
            profile: "Profile",
            thanks: "Thanks",
            centerText: "It looks like you don't have any projects yet.<br>Create a new one or import!",
            ThanksCommunity: "Thanks from the Ecrous Engine community!",
            Autors: "Authors",
            Donors: "Donors",
            License: "License",
            HappyBirsday: "B-Day!",
            HappyBirsdayEnd: "B-Day End",
            DaniilDomashnev: "Daniil Domashnev",
            ThemEditor: "Theme Editor:",
            ThemBlack: "Dark",
            ThemWhite: "Light",
            russian: "Russian",
            english: "English",
            ukraine: "Ukrainian",
            espano: "Spanish",
            deutsch: "German",
            FilePath: "FilePath:",
            Gravity: "Gravity",
            Review: "Review",
            Settings: "Settings",
            Community: "Community",
            Profile: "Profile",
            OpenProfile: "Change Name",
            Promocodes: "Promocodes",
            InputPromocode: "Input Promocode",
            ApplyPromocode: "Apply Promocode",
            labelfonts: "Font:",
        },
        uk: {
            labelLanguage: "Мова:",
            loadingTitle: "Завантаження Ecrous Engine...",
            loadingMessage: "Не хвилюйтеся, через кілька секунд все буде готово!",
            myProjects: "Мої проекти",
            xStore: "XStore",
            blackStore: "BlackStoreRu",
            profile: "Профіль",
            thanks: "Дякую",
            centerText: "Схоже, у вас ще немає проектів.<br>Створіть новий або імпортуйте!",
            ThanksCommunity: "Дякуємо від спільноти Ecrous Engine!",
            Autors: "Автори",
            Donors: "Донори",
            License: "Ліцензія",
            HappyBirsday: "З днем народження!",
            HappyBirsdayEnd: "Минулі ДР",
            DaniilDomashnev: "Данило Домашнєв",
            ThemEditor: "Редактор теми:",
            ThemBlack: "Темна",
            ThemWhite: "Світла",
            russian: "Російська",
            english: "Англійська",
            ukraine: "Українська",
            espano: "Іспанська",
            deutsch: "Німецька",
            FilePath: "Шлях до файлу:",
            Gravity: "Гравітація",
            Review: "Огляд",
            Settings: "Налаштування",
            Community: "Спільнота",
            Profile: "Профіль",
            OpenProfile: "Відкрити профіль",
            Promocodes: "Промокоди",
            InputPromocode: "Введіть промокод",
            ApplyPromocode: "Застосувати промокод"
        },
        kz: {
            labelLanguage: "Тіл:",
            loadingTitle: "Ecrous Engine жүктелуде...",
            loadingMessage: "Қатты уайымдамаңыз, бірнеше секундтан кейін дайын болады!",
            myProjects: "Менің жобаларым",
            xStore: "XStore",
            blackStore: "BlackStoreRu",
            profile: "Профиль",
            thanks: "Рахмет",
            centerText: "Сізде жобалар жоқ сияқты.<br>Жаңа жобаны жасаңыз немесе импорттаңыз!",
            ThanksCommunity: "Ecrous Engine қоғамынан алғысымызды білдіреміз!",
            Autors: "Авторлар",
            Donors: "Донорлар",
            License: "Лицензия",
            HappyBirsday: "Туған күн!",
            HappyBirsdayEnd: "Өткен туған күндер",
            DaniilDomashnev: "Даниил Домашнев",
            ThemEditor: "Редактор тақырыбы:",
            ThemBlack: "Қара",
            ThemWhite: "Ақ",
            russian: "Орысша",
            english: "Ағылшынша",
            ukraine: "Украинша",
            kazak: "Қазақша",
            espano: "Испанша",
            deutsch: "Немісше",
            FilePath: "Файл жолы:",
            Gravity: "Гравитация",
            Review: "Шолу",
            Settings: "Параметрлер",
            Community: "Қоғамдастық",
            Profile: "Профиль",
            OpenProfile: "Профильді ашу",
            Promocodes: "Промокодтар",
            InputPromocode: "Промокодты енгізіңіз",
            ApplyPromocode: "Промокодты қолдану"
        },
        pl: {
            labelLanguage: "Język:",
            loadingTitle: "Ładowanie Ecrous Engine...",
            loadingMessage: "Nie martw się, wszystko będzie gotowe za kilka sekund!",
            myProjects: "Moje Projekty",
            xStore: "XStore",
            blackStore: "BlackStoreRu",
            profile: "Profil",
            thanks: "Dziękuję",
            centerText: "Wygląda na to, że nie masz jeszcze projektów.<br>Utwórz nowy lub zaimportuj!",
            ThanksCommunity: "Podziękowania od społeczności Ecrous Engine!",
            Autors: "Autorzy",
            Donors: "Darczyńcy",
            License: "Licencja",
            HappyBirsday: "Urodziny!",
            HappyBirsdayEnd: "Minione urodziny",
            DaniilDomashnev: "Daniil Domashnev",
            ThemEditor: "Motyw Edytora:",
            ThemBlack: "Ciemny",
            ThemWhite: "Jasny",
            russian: "Rosyjski",
            english: "Angielski",
            ukraine: "Ukraiński",
            kazak: "Kazachski",
            espano: "Hiszpański",
            deutsch: "Niemiecki",
            FilePath: "Ścieżka do pliku:",
            Gravity: "Grawitacja",
            Review: "Przegląd",
            Settings: "Ustawienia",
            Community: "Społeczność",
            Profile: "Profil",
            OpenProfile: "Otwórz Profil",
            Promocodes: "Kody Promocyjne",
            InputPromocode: "Wprowadź Kod Promocyjny",
            ApplyPromocode: "Zastosuj Kod Promocyjny"
        },
        es: {
            labelLanguage: "Idioma:",
            loadingTitle: "Cargando Ecrous Engine...",
            loadingMessage: "¡No te preocupes, todo estará listo en unos segundos!",
            myProjects: "Mis Proyectos",
            xStore: "XStore",
            blackStore: "BlackStoreRu",
            profile: "Perfil",
            thanks: "Gracias",
            centerText: "Parece que aún no tienes proyectos.<br>¡Crea uno nuevo o importa!",
            ThanksCommunity: "¡Gracias de parte de la comunidad de Ecrous Engine!",
            Autors: "Autores",
            Donors: "Donantes",
            License: "Licencia",
            HappyBirsday: "¡Feliz Cumpleaños!",
            HappyBirsdayEnd: "Cumpleaños Pasados",
            DaniilDomashnev: "Daniil Domashnev",
            ThemEditor: "Tema del Editor:",
            ThemBlack: "Oscuro",
            ThemWhite: "Claro",
            russian: "Ruso",
            english: "Inglés",
            ukraine: "Ucraniano",
            kazak: "Kazajo",
            espano: "Español",
            deutsch: "Alemán",
            FilePath: "Ruta del Archivo:",
            Gravity: "Gravedad",
            Review: "Revisión",
            Settings: "Configuración",
            Community: "Comunidad",
            Profile: "Perfil",
            OpenProfile: "Abrir Perfil",
            Promocodes: "Códigos Promocionales",
            InputPromocode: "Ingresar Código Promocional",
            ApplyPromocode: "Aplicar Código Promocional"
        },
        de: {
            labelLanguage: "Sprache",
            loadingTitle: "Laden Ecrous Engine...",
            loadingMessage: "Keine Sorge, in ein paar Sekunden ist alles fertig!",
            myProjects: "Meine Projekte",
            xStore: "XStore",
            blackStore: "BlackStoreRu",
            profile: "Profil",
            thanks: "Danke",
            centerText: "Es sieht so aus, als hätten Sie noch keine Projekte.<br>Erstellen Sie ein neues oder importieren Sie es!",
            ThanksCommunity: "Ecrous Engine!",
            Autors: "Autoren",
            Donors: "Spender",
            License: "Lizenz",
            HappyBirsday: "Alles Gute zum Geburtstag",
            HappyBirsdayEnd: "",
            DaniilDomashnev: "Daniil Domashnev",
            ThemEditor: "Editor-Theme",
            ThemBlack: "Dunkles Thema",
            ThemWhite: "Helles Thema",
            russian: "Russisch",
            english: "Englisch",
            ukraine: "Ukrainisch",
            kazak: "Kasachisch",
            espano: "Spanisch",
            deutsch: "Deutsch",
            FilePath: "Dateipfad",
            Gravity: "Schwerkraft",
            Review: "Bewertung",
            Settings: "Einstellungen",
            Community: "Community",
            Profile: "Profil",
            OpenProfile: "Profil öffnen",
            Promocodes: "Promocodes",
            InputPromocode: "Promocode eingeben",
            ApplyPromocode: "Promocode anwenden"
        }
    };

    // Функция обновления текста
    function updateTranslations(language) {
        translateElements.forEach((element) => {
            const key = element.getAttribute("data-translate");
            if (translations[language] && translations[language][key]) {
                element.textContent = translations[language][key];
                element.innerHTML = translations[language][key];
            }
        });
    }

    // Проверка LocalStorage на сохраненный язык
    const savedLanguage = localStorage.getItem("language") || "ru";
    languageSelect.value = savedLanguage;
    updateTranslations(savedLanguage);

    // Сохранение языка и обновление текста при изменении
    languageSelect.addEventListener("change", (event) => {
        const selectedLanguage = event.target.value;
        localStorage.setItem("language", selectedLanguage); // Сохранение в LocalStorage
        updateTranslations(selectedLanguage);
    });
});
